# Site settings
title: DizzBoy的小站~ # 你的博客名字，可以定义修订
header-img: "http://wx2.sinaimg.cn/mw690/006WKNnMgy1ftr21biu21j31hc0u01j0.jpg"
tagline: "cn"  
description: "一个蓝星人的博客"  # 一句话描述你的博客
baseurl: ""
url: "http://dizzboy.github.io"  # 此处填写你的博客地址

# About/contact
owner: 
  name: "Feiht" # 填写作者信息：名字
  email: X@gmail.com # 填写作者信息：邮箱
  bio: "你的博客描述" # 填写作者信息：博客描述

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username: 
github_username: DizzBoy
facebook_username: 
weibo_username: 
zhihu_username: xiao-en-7-71

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: rdiscount
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/WuHan
plugins: [jekyll-paginate]
# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "DizzBoy" # 你的名字
      header-img: "http://wx4.sinaimg.cn/mw690/006WKNnMgy1ftr1z10t45j31hc0u04qp.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name :  # 填写你的 disqus id
  disqus :
      short_name :  # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics: UA-123076533-1 # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
